version: '2'
services:
  musicbrainzsearch-app:
    image: musicbrainzsearch
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://musicbrainzsearch-postgresql:5432/musicbrainzsearch
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://musicbrainzsearch-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://musicbrainzsearch-elasticsearch:9200
    ports:
      - 8080:8080
  musicbrainzsearch-postgresql:
    extends:
      file: postgresql.yml
      service: musicbrainzsearch-postgresql
  musicbrainzsearch-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: musicbrainzsearch-elasticsearch
